name: unpublish-image
on: workflow_dispatch
jobs:
  unpublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: npm unpublish @prsm/image --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
